# """
# Django settings for LoginPage project.
#
# Generated by 'django-admin startproject' using Django 4.1.7.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.1/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.1/ref/settings/
# """
import os.path
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+s#wcz!tw2^j!#dzpu4o2hlc^rne*dag*6a4q6r1tpj1$)nk=p"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'localhost:8000']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "csp",
    "corsheaders",
    "app1",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Place CorsMiddleware before other middleware
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "csp.middleware.CSPMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'https://cdn.jsdelivr.net',
    'https://fonts.gstatic.com',
    'https://fonts.googleapis.com',
    'https://cdnjs.cloudflare.com',
    'https://stackpath.bootstrapcdn.com',
    'http://127.0.1:8000',
]

ROOT_URLCONF = "LoginPage.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'csp.context_processors.nonce',
            ],
        },
    },
]

WSGI_APPLICATION = "LoginPage.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gurupruthvi61@gmail.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

X_FRAME_OPTIONS = 'SAMEORIGIN'

# CORS_ALLOWED_ORIGINS = [
#     "https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css",
#     "https://fonts.gstatic.com",
#     "https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap",
#     "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
#     "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css",
#     "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap",
#     "http://127.0.1:8000/static"
# ]

# CORS_ALLOWED_ORIGINS = [
#     "https://cdn.jsdelivr.net",
#     "https://fonts.gstatic.com",
#     "https://fonts.googleapis.com",
#     "https://cdnjs.cloudflare.com",
#     "https://stackpath.bootstrapcdn.com",
#     "https://fonts.googleapis.com",
#     'http://localhost:8000',
# ]

CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', ]
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = (
    "'self'",
    "https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css",
    "https://fonts.gstatic.com",
    "https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap",
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
    "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css")
CSP_FONT_SRC = (
    "'self'", "https://fonts.gstatic.com",
    "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap")

CORS_ALLOW_ALL_ORIGINS = False

# Low
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

"""
Django settings for LoginPage project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# import os.path
# from pathlib import Path
# from decouple import config
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-+s#wcz!tw2^j!#dzpu4o2hlc^rne*dag*6a4q6r1tpj1$)nk=p"
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
# CSRF_COOKIE_HTTPONLY = True
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_HTTPONLY=True
#
#
# ALLOWED_HOSTS = ["hpecty.pythonanywhere.com"]
#
# # Application definition
#
# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     'csp',
#     'corsheaders',
#     "app1",
# ]
#
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     'corsheaders.middleware.CorsMiddleware',
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'csp.middleware.CSPMiddleware',
# ]
#
#
# ROOT_URLCONF = "LoginPage.urls"
#
# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": ['templates'],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = "LoginPage.wsgi.application"
#
# # Database
# # https://docs.djangoproject.com/en/4.1/ref/settings/#databases
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
#
# # Password validation
# # https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
# ]
#
# # Internationalization
# # https://docs.djangoproject.com/en/4.1/topics/i18n/
#
# LANGUAGE_CODE = "en-us"
#
# TIME_ZONE = "UTC"
#
# USE_I18N = True
#
# USE_TZ = True
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.1/howto/static-files/
#
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
#
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'gurupruthvi61@gmail.com'
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
#
#
#
#
# CORS_ALLOWED_ORIGINS = [
#     "https://hpecty.pythonanywhere.com"
# ]
#
# CSRF_TRUSTED_ORIGINS = [
#     "https://hpecty.pythonanywhere.com"
# ]
# CORS_ORIGIN_WITELIST=["https://hpecty.pythonanywhere.com"]
#
#
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_STYLE_SRC = ( "'self'",
#                 "https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css",
#                 "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
#                 "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css")
# CSP_FONT_SRC = ("'self'",
#                 "https://fonts.gstatic.com",
#                 "https://fonts.googleapis.com/",
#     )
#
# CORS_ALLOW_ALL_ORIGINS = False
