# Generated by Django 3.2.15 on 2023-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('userquery', models.TextField(default='NULL')),
            ],
        ),
    ]
